### ISSUE TITLE
Rescale the  flow

### ISSUE THREAD

**Issue by MedicalReg** [ivan-jgr/recursive-cascaded-networks#3]
Hi! Thank your hard work. 
I notice that there is an unreasonable design in VTN. The flow should not be multiplied by 20. It's too much! I guess that it is because there are some differences in transformation layers between Pytorch and Tensorflow. I recommend that readers multiply the flow with values less than 1.0, and it works in my implementations.

**Comment by ivan-jgr** [comment]
Hi @MedicalReg, that seems a little unreasonable for me, I'm redoing this work with some changes. I've found that a value less than 1.0 works perfectly.

Thanks.
