### ISSUE TITLE
Hi, I have a question

### ISSUE THREAD

**Issue by BTRFusion** [ivan-jgr/recursive-cascaded-networks#4]
Hi. Great work is done! Thank you for sharing this code.
run:
python train.py
FileNotFoundError: [Errno 2] No such file or directory: './train.txt'
Where is this file 'train.txt'

Looking forward to your reply.

**Comment by ivan-jgr** [comment]
Hi, the loader in this repository was custom made, depend on your data you'll need to write your own loader.

This loader uses two files: `train.txt` and `val.txt` file with the following structure:
```
fixed_image_path_1,moving_image_path_1
fixed_image_path_2,moving_image_path_2
```
