### ISSUE TITLE
question about “the final output is a composition of all predicted flow fields”

### ISSUE THREAD

**Issue by B1GGUN** [ivan-jgr/recursive-cascaded-networks#5]
Thank you for the code！
In the paper ‘the final output is a composition of all predicted flow fields’. Where is the code for this step？
<img width="355" alt="微信图片_20221203004313" src="https://user-images.githubusercontent.com/45312468/205342309-a12296d6-2f75-4c1b-896d-0546a41ed6e0.png">
Looking forward to your reply！

**Comment by ivan-jgr** [comment]
Hi!, 
The composition starts here:

https://github.com/ivan-jgr/recursive-cascaded-networks/blob/2107c7f46b06715580f826a1f3bf53c887ba2b90/networks/recursive_cascade_networks.py#L34

`self.stems` contains the models for each cascade and the forward method for each one of them gives you the ϕ_n flow field.

**Comment by B1GGUN** [comment]
Hi！
https://github.com/ivan-jgr/recursive-cascaded-networks/blob/2107c7f46b06715580f826a1f3bf53c887ba2b90/networks/recursive_cascade_networks.py#L34
line 34-38 in recursive_cascade_networks.py seem to be just a cascade process.  flows[ ] saves the flow field of each cascaded subnet and stem_results[ ] saves the warped image. 
Then you just return these two lists and do not compute the composition of all the predicted flow fields, like the code below：
https://github.com/microsoft/Recursive-Cascaded-Networks/blob/0709490fe010e4acc6357990d1d871c170e3ef31/network/recursive_cascaded_networks.py#L99
Maybe I'm missing something in your code, if there is this step please tell me where it is, thanks!

**Comment by ivan-jgr** [comment]
Let's see the equation (4) and (5) in the paper
![image](https://user-images.githubusercontent.com/13913074/206960956-560346a9-00c6-4ea5-abe7-003eb7150bd9.png)

The flow field you are talking about is $F(I_m, I_f)$ and you're right, in this implementation $F(I_m, I_f)$  is no explicitly.
I calculate the final warped image via (5), i.e.
$$I_{warped} = F(I_m, I_f) \circ I_m = (\phi_n \circ \cdots \circ \phi_1) \circ I_m$$

But applying the definition of composition:
$$(\phi_n \circ \cdots \circ \phi_1) \circ I_m = (\phi_n \circ \cdots \circ \phi_2) \circ (\phi_1 \circ I_m)$$

Note that in the first iteration of lines `34-38` you get the first composition $(\phi_1 \circ I_m) = I_m^{(1)}$, and so on.

This is equivalent to compose all the flow fields $\phi_n$ as in the link you provide.

I don't know if this is a good explanation 😅 but for all maters it is equivalent.

Let me know if I can help.

**Comment by B1GGUN** [comment]
thanks!
